<?php

namespace App\Http\Controllers;

use Inertia\Inertia;
use Inertia\Response;

class CatalogController extends Controller
{
    /**
     * Show the game catalog with search and filters.
     */
    public function index(): Response
    {
        return Inertia::render('Catalog', [
            'games' => $this->allGames(),
            'genres' => [
                'Action',
                'RPG',
                'Simulation',
                'Strategy',
                'Sports',
                'Horror',
                'Adventure',
                'Sci-Fi',
            ],
            'platforms' => [
                ['value' => 'windows', 'label' => 'Windows'],
                ['value' => 'mac', 'label' => 'Mac'],
                ['value' => 'linux', 'label' => 'Linux'],
                ['value' => 'playstation', 'label' => 'PlayStation'],
                ['value' => 'xbox', 'label' => 'Xbox'],
                ['value' => 'nintendo', 'label' => 'Nintendo'],
            ],
            'priceRanges' => [
                ['label' => 'Under $10', 'min' => 0, 'max' => 10],
                ['label' => '$10 - $30', 'min' => 10, 'max' => 30],
                ['label' => '$30 - $50', 'min' => 30, 'max' => 50],
                ['label' => '$50+', 'min' => 50, 'max' => null],
            ],
            'ratings' => [4, 3, 2, 1],
        ]);
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function allGames(): array
    {
        return [
            [
                'id' => 1,
                'title' => 'Cyber Legends',
                'slug' => 'cyber-legends',
                'description' => 'In a world where technology and humanity collide, fight for survival in the neon-lit streets of Neo Tokyo.',
                'price' => '59.99',
                'discount_price' => '39.99',
                'discount_pct' => 33,
                'is_discounted' => true,
                'release_date' => '2025-06-15',
                'developer' => 'NeonPixel Games',
                'publisher' => 'Digital Dreams Publishing',
                'genre' => 'Action',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Cyber+Legends',
                'rating_avg' => 4.5,
                'rating_count' => 1250,
            ],
            [
                'id' => 2,
                'title' => 'Star Voyager',
                'slug' => 'star-voyager',
                'description' => 'Explore the uncharted reaches of deep space in this epic sci-fi adventure.',
                'price' => '49.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2025-03-20',
                'developer' => 'Cosmic Forge',
                'publisher' => 'Stellar Interactive',
                'genre' => 'Sci-Fi',
                'platforms' => ['windows', 'mac', 'linux'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Star+Voyager',
                'rating_avg' => 4.2,
                'rating_count' => 980,
            ],
            [
                'id' => 3,
                'title' => "Dragon's Curse",
                'slug' => 'dragons-curse',
                'description' => 'An ancient curse threatens the kingdom. Only you can wield the dragon flame.',
                'price' => '39.99',
                'discount_price' => '19.99',
                'discount_pct' => 50,
                'is_discounted' => true,
                'release_date' => '2024-11-01',
                'developer' => 'Mythic Studios',
                'publisher' => 'Fantasy World Entertainment',
                'genre' => 'RPG',
                'platforms' => ['windows', 'playstation', 'xbox', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Dragon%27s+Curse',
                'rating_avg' => 4.8,
                'rating_count' => 2100,
            ],
            [
                'id' => 4,
                'title' => 'City Builder Pro',
                'slug' => 'city-builder-pro',
                'description' => 'Design, build, and manage the ultimate metropolis.',
                'price' => '29.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2025-01-10',
                'developer' => 'Urban Play',
                'publisher' => 'Simulation Masters',
                'genre' => 'Simulation',
                'platforms' => ['windows', 'mac'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=City+Builder+Pro',
                'rating_avg' => 4.0,
                'rating_count' => 650,
            ],
            [
                'id' => 5,
                'title' => 'Shadow Strike',
                'slug' => 'shadow-strike',
                'description' => 'Stealth and precision define this tactical action thriller.',
                'price' => '44.99',
                'discount_price' => '35.99',
                'discount_pct' => 20,
                'is_discounted' => true,
                'release_date' => '2025-04-05',
                'developer' => 'Black Ops Interactive',
                'publisher' => 'StealthWorks',
                'genre' => 'Action',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Shadow+Strike',
                'rating_avg' => 4.3,
                'rating_count' => 780,
            ],
            [
                'id' => 6,
                'title' => 'Mystic Woods',
                'slug' => 'mystic-woods',
                'description' => 'A magical forest holds secrets that could change the world forever.',
                'price' => '34.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-07-22',
                'developer' => 'Enchanted Byte',
                'publisher' => 'Fantasy World Entertainment',
                'genre' => 'RPG',
                'platforms' => ['windows', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Mystic+Woods',
                'rating_avg' => 4.6,
                'rating_count' => 1500,
            ],
            [
                'id' => 7,
                'title' => 'Racing Evolution',
                'slug' => 'racing-evolution',
                'description' => 'Feel the need for speed in the most realistic racing game ever made.',
                'price' => '49.99',
                'discount_price' => '37.49',
                'discount_pct' => 25,
                'is_discounted' => true,
                'release_date' => '2024-09-15',
                'developer' => 'Turbocharge Games',
                'publisher' => 'Speedway Interactive',
                'genre' => 'Sports',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Racing+Evolution',
                'rating_avg' => 3.9,
                'rating_count' => 3400,
            ],
            [
                'id' => 8,
                'title' => 'Galactic War',
                'slug' => 'galactic-war',
                'description' => 'Command fleets and conquer galaxies in this grand strategy epic.',
                'price' => '19.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-05-10',
                'developer' => 'StarCraft Studios',
                'publisher' => 'Grand Strategy Inc',
                'genre' => 'Strategy',
                'platforms' => ['windows', 'mac', 'linux'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Galactic+War',
                'rating_avg' => 4.1,
                'rating_count' => 890,
            ],
            [
                'id' => 9,
                'title' => 'Haunted Asylum',
                'slug' => 'haunted-asylum',
                'description' => 'Survive the horrors that lurk within the abandoned wards.',
                'price' => '29.99',
                'discount_price' => '17.99',
                'discount_pct' => 40,
                'is_discounted' => true,
                'release_date' => '2024-10-31',
                'developer' => 'Dark Alley Games',
                'publisher' => 'Horror Interactive',
                'genre' => 'Horror',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Haunted+Asylum',
                'rating_avg' => 4.4,
                'rating_count' => 1800,
            ],
            [
                'id' => 10,
                'title' => 'Pixel Quest',
                'slug' => 'pixel-quest',
                'description' => 'A nostalgic adventure through a beautifully crafted pixel world.',
                'price' => '14.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-03-01',
                'developer' => 'RetroForge',
                'publisher' => 'Pixel Perfect Games',
                'genre' => 'Adventure',
                'platforms' => ['windows', 'mac', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Pixel+Quest',
                'rating_avg' => 4.7,
                'rating_count' => 2200,
            ],
            [
                'id' => 11,
                'title' => 'Kingdom Reborn',
                'slug' => 'kingdom-reborn',
                'description' => 'Lead your kingdom from ruin to glory in this medieval strategy game.',
                'price' => '39.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2025-02-14',
                'developer' => 'Castleforge Interactive',
                'publisher' => 'Grand Strategy Inc',
                'genre' => 'Strategy',
                'platforms' => ['windows', 'mac'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Kingdom+Reborn',
                'rating_avg' => 4.3,
                'rating_count' => 720,
            ],
            [
                'id' => 12,
                'title' => 'Frozen Tundra',
                'slug' => 'frozen-tundra',
                'description' => 'Brave the arctic wasteland in this survival action game.',
                'price' => '44.99',
                'discount_price' => '38.24',
                'discount_pct' => 15,
                'is_discounted' => true,
                'release_date' => '2024-12-01',
                'developer' => 'North Pole Studios',
                'publisher' => 'SurvivalCraft',
                'genre' => 'Action',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Frozen+Tundra',
                'rating_avg' => 4.0,
                'rating_count' => 430,
            ],
            [
                'id' => 13,
                'title' => 'Space Marines',
                'slug' => 'space-marines',
                'description' => 'Join the elite forces defending Earth from alien threats.',
                'price' => '59.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2025-05-20',
                'developer' => 'Orbital Games',
                'publisher' => 'Digital Dreams Publishing',
                'genre' => 'Sci-Fi',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Space+Marines',
                'rating_avg' => 3.8,
                'rating_count' => 560,
            ],
            [
                'id' => 14,
                'title' => 'The Lost City',
                'slug' => 'the-lost-city',
                'description' => 'Discover the secrets of an ancient civilization buried beneath the sand.',
                'price' => '24.99',
                'discount_price' => '17.49',
                'discount_pct' => 30,
                'is_discounted' => true,
                'release_date' => '2024-08-15',
                'developer' => 'Desert Fox Studios',
                'publisher' => 'Pixel Perfect Games',
                'genre' => 'Adventure',
                'platforms' => ['windows', 'mac', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=The+Lost+City',
                'rating_avg' => 4.5,
                'rating_count' => 1100,
            ],
            [
                'id' => 15,
                'title' => 'Farming Tycoon',
                'slug' => 'farming-tycoon',
                'description' => 'Build your agricultural empire from a single plot of land.',
                'price' => '19.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-04-10',
                'developer' => 'Green Fields Interactive',
                'publisher' => 'Simulation Masters',
                'genre' => 'Simulation',
                'platforms' => ['windows', 'mac', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Farming+Tycoon',
                'rating_avg' => 4.2,
                'rating_count' => 890,
            ],
            [
                'id' => 16,
                'title' => 'Night Stalkers',
                'slug' => 'night-stalkers',
                'description' => 'They only come out at night. And they are hungry.',
                'price' => '34.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2025-07-20',
                'developer' => 'Dark Alley Games',
                'publisher' => 'Horror Interactive',
                'genre' => 'Horror',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Night+Stalkers',
                'rating_avg' => 4.1,
                'rating_count' => 340,
            ],
            [
                'id' => 17,
                'title' => 'Ultimate Fighter',
                'slug' => 'ultimate-fighter',
                'description' => 'Step into the ring and become the champion.',
                'price' => '49.99',
                'discount_price' => '32.49',
                'discount_pct' => 35,
                'is_discounted' => true,
                'release_date' => '2024-06-30',
                'developer' => 'Knockout Games',
                'publisher' => 'Speedway Interactive',
                'genre' => 'Sports',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Ultimate+Fighter',
                'rating_avg' => 3.7,
                'rating_count' => 1200,
            ],
            [
                'id' => 18,
                'title' => 'Dungeon Crawlers',
                'slug' => 'dungeon-crawlers',
                'description' => 'Gather your party and venture into the depths of the underworld.',
                'price' => '44.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-12-15',
                'developer' => 'Mythic Studios',
                'publisher' => 'Fantasy World Entertainment',
                'genre' => 'RPG',
                'platforms' => ['windows', 'mac', 'linux', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Dungeon+Crawlers',
                'rating_avg' => 4.6,
                'rating_count' => 980,
            ],
            [
                'id' => 19,
                'title' => 'Ocean Explorer',
                'slug' => 'ocean-explorer',
                'description' => 'Dive into the depths of the ocean and discover its wonders.',
                'price' => '29.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2025-08-01',
                'developer' => 'Deep Blue Interactive',
                'publisher' => 'Pixel Perfect Games',
                'genre' => 'Adventure',
                'platforms' => ['windows', 'playstation', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Ocean+Explorer',
                'rating_avg' => 4.0,
                'rating_count' => 290,
            ],
            [
                'id' => 20,
                'title' => 'Tower Defense X',
                'slug' => 'tower-defense-x',
                'description' => 'Build, upgrade, and defend against endless waves of enemies.',
                'price' => '9.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-02-14',
                'developer' => 'Strategy First',
                'publisher' => 'Grand Strategy Inc',
                'genre' => 'Strategy',
                'platforms' => ['windows', 'mac', 'linux', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Tower+Defense+X',
                'rating_avg' => 4.4,
                'rating_count' => 1500,
            ],
            [
                'id' => 21,
                'title' => 'Neo Tokyo Drift',
                'slug' => 'neo-tokyo-drift',
                'description' => 'Street racing meets cyberpunk in the neon-lit streets of Neo Tokyo.',
                'price' => '39.99',
                'discount_price' => '21.99',
                'discount_pct' => 45,
                'is_discounted' => true,
                'release_date' => '2025-09-15',
                'developer' => 'Turbocharge Games',
                'publisher' => 'Speedway Interactive',
                'genre' => 'Action',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Neo+Tokyo+Drift',
                'rating_avg' => 4.2,
                'rating_count' => 670,
            ],
            [
                'id' => 22,
                'title' => 'Fantasy Realm',
                'slug' => 'fantasy-realm',
                'description' => 'A sprawling open-world RPG where your choices shape the world.',
                'price' => '54.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-01-20',
                'developer' => 'Mythic Studios',
                'publisher' => 'Fantasy World Entertainment',
                'genre' => 'RPG',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Fantasy+Realm',
                'rating_avg' => 4.8,
                'rating_count' => 3100,
            ],
            [
                'id' => 23,
                'title' => 'Zombie Outbreak',
                'slug' => 'zombie-outbreak',
                'description' => 'The apocalypse is here. How long can you survive?',
                'price' => '24.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-10-05',
                'developer' => 'Undead Labs',
                'publisher' => 'Horror Interactive',
                'genre' => 'Horror',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Zombie+Outbreak',
                'rating_avg' => 3.9,
                'rating_count' => 2100,
            ],
            [
                'id' => 24,
                'title' => 'Construction Sim',
                'slug' => 'construction-sim',
                'description' => 'Build massive structures with realistic construction machinery.',
                'price' => '34.99',
                'discount_price' => '27.99',
                'discount_pct' => 20,
                'is_discounted' => true,
                'release_date' => '2024-03-15',
                'developer' => 'BuildMaster Games',
                'publisher' => 'Simulation Masters',
                'genre' => 'Simulation',
                'platforms' => ['windows', 'mac', 'playstation'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Construction+Sim',
                'rating_avg' => 4.3,
                'rating_count' => 780,
            ],
            [
                'id' => 25,
                'title' => 'Astro Miner',
                'slug' => 'astro-miner',
                'description' => 'Mine asteroids, build your ship, explore the galaxy.',
                'price' => '19.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2025-10-01',
                'developer' => 'Cosmic Forge',
                'publisher' => 'Stellar Interactive',
                'genre' => 'Sci-Fi',
                'platforms' => ['windows', 'mac', 'linux'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Astro+Miner',
                'rating_avg' => 4.1,
                'rating_count' => 450,
            ],
            [
                'id' => 26,
                'title' => 'Legend of the Blade',
                'slug' => 'legend-of-the-blade',
                'description' => 'Master the blade and become the warrior of prophecy.',
                'price' => '49.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2025-11-15',
                'developer' => 'NeonPixel Games',
                'publisher' => 'Digital Dreams Publishing',
                'genre' => 'Action',
                'platforms' => ['windows', 'playstation', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Legend+of+the+Blade',
                'rating_avg' => 4.7,
                'rating_count' => 890,
            ],
            [
                'id' => 27,
                'title' => "Pirate's Bounty",
                'slug' => 'pirates-bounty',
                'description' => 'Hoist the sails and seek treasure on the high seas!',
                'price' => '29.99',
                'discount_price' => '14.99',
                'discount_pct' => 50,
                'is_discounted' => true,
                'release_date' => '2024-09-19',
                'developer' => 'Sea Dog Studios',
                'publisher' => 'Pixel Perfect Games',
                'genre' => 'Adventure',
                'platforms' => ['windows', 'playstation', 'xbox', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Pirate%27s+Bounty',
                'rating_avg' => 4.4,
                'rating_count' => 1300,
            ],
            [
                'id' => 28,
                'title' => 'Grand Prix Manager',
                'slug' => 'grand-prix-manager',
                'description' => 'Manage your Formula One team to championship glory.',
                'price' => '39.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2025-04-20',
                'developer' => 'Pit Crew Interactive',
                'publisher' => 'Speedway Interactive',
                'genre' => 'Sports',
                'platforms' => ['windows', 'mac'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Grand+Prix+Manager',
                'rating_avg' => 4.0,
                'rating_count' => 560,
            ],
            [
                'id' => 29,
                'title' => 'Dark Descent',
                'slug' => 'dark-descent',
                'description' => 'Descend into madness in this psychological horror experience.',
                'price' => '44.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-10-31',
                'developer' => 'Dark Alley Games',
                'publisher' => 'Horror Interactive',
                'genre' => 'Horror',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Dark+Descent',
                'rating_avg' => 4.5,
                'rating_count' => 1600,
            ],
            [
                'id' => 30,
                'title' => 'Chess Master Elite',
                'slug' => 'chess-master-elite',
                'description' => 'The ultimate chess experience with AI-powered opponents.',
                'price' => '9.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-01-05',
                'developer' => 'Strategy First',
                'publisher' => 'Grand Strategy Inc',
                'genre' => 'Strategy',
                'platforms' => ['windows', 'mac', 'linux', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Chess+Master+Elite',
                'rating_avg' => 4.9,
                'rating_count' => 2800,
            ],
        ];
    }
}
