<?php

namespace App\Http\Controllers;

use Inertia\Inertia;
use Inertia\Response;

class HomeController extends Controller
{
    /**
     * Show the home page with hero carousel and game sections.
     */
    public function index(): Response
    {
        $allGames = $this->allGames();

        return Inertia::render('Home', [
            'featuredGames' => array_slice($allGames, 0, 5),
            'newReleases' => array_slice($allGames, 0, 12),
            'topRated' => collect($allGames)->sortByDesc('rating_avg')->take(12)->values()->all(),
            'comingSoon' => collect($allGames)->filter(fn ($g) => $g['coming_soon'])->take(12)->values()->all(),
            'onSale' => collect($allGames)->filter(fn ($g) => $g['is_discounted'])->take(12)->values()->all(),
        ]);
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function allGames(): array
    {
        return [
            [
                'id' => 1,
                'title' => 'Cyber Legends',
                'slug' => 'cyber-legends',
                'description' => 'In a world where technology and humanity collide, fight for survival in the neon-lit streets of Neo Tokyo.',
                'about' => 'Cyber Legends is an immersive action game set in a dystopian cyberpunk future. Hack, slash, and shoot your way through corporate armies.',
                'price' => '59.99',
                'discount_price' => '39.99',
                'discount_pct' => 33,
                'is_discounted' => true,
                'release_date' => '2025-06-15',
                'developer' => 'NeonPixel Games',
                'publisher' => 'Digital Dreams Publishing',
                'genre' => 'Action',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Cyber+Legends',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Cyber+Legends',
                'rating_avg' => 4.5,
                'rating_count' => 1250,
                'coming_soon' => false,
            ],
            [
                'id' => 2,
                'title' => 'Star Voyager',
                'slug' => 'star-voyager',
                'description' => 'Explore the uncharted reaches of deep space in this epic sci-fi adventure.',
                'about' => 'Star Voyager takes you on a journey across the galaxy. Discover new worlds, build alliances, and uncover ancient mysteries.',
                'price' => '49.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2025-03-20',
                'developer' => 'Cosmic Forge',
                'publisher' => 'Stellar Interactive',
                'genre' => 'Sci-Fi',
                'platforms' => ['windows', 'mac', 'linux'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Star+Voyager',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Star+Voyager',
                'rating_avg' => 4.2,
                'rating_count' => 980,
                'coming_soon' => false,
            ],
            [
                'id' => 3,
                'title' => "Dragon's Curse",
                'slug' => 'dragons-curse',
                'description' => 'An ancient curse threatens the kingdom. Only you can wield the dragon flame.',
                'about' => "Dragon's Curse is an epic RPG where you play as the last dragonborn. Master elemental magic, forge legendary weapons, and save the realm.",
                'price' => '39.99',
                'discount_price' => '19.99',
                'discount_pct' => 50,
                'is_discounted' => true,
                'release_date' => '2024-11-01',
                'developer' => 'Mythic Studios',
                'publisher' => 'Fantasy World Entertainment',
                'genre' => 'RPG',
                'platforms' => ['windows', 'playstation', 'xbox', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Dragon%27s+Curse',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Dragon%27s+Curse',
                'rating_avg' => 4.8,
                'rating_count' => 2100,
                'coming_soon' => false,
            ],
            [
                'id' => 4,
                'title' => 'City Builder Pro',
                'slug' => 'city-builder-pro',
                'description' => 'Design, build, and manage the ultimate metropolis.',
                'about' => 'City Builder Pro puts you in the mayor\'s seat. Zone districts, manage resources, and keep your citizens happy in this deep simulation.',
                'price' => '29.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2025-01-10',
                'developer' => 'Urban Play',
                'publisher' => 'Simulation Masters',
                'genre' => 'Simulation',
                'platforms' => ['windows', 'mac'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=City+Builder+Pro',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=City+Builder+Pro',
                'rating_avg' => 4.0,
                'rating_count' => 650,
                'coming_soon' => false,
            ],
            [
                'id' => 5,
                'title' => 'Shadow Strike',
                'slug' => 'shadow-strike',
                'description' => 'Stealth and precision define this tactical action thriller.',
                'about' => 'Shadow Strike is a tactical stealth game where every move matters. Infiltrate enemy bases, eliminate targets silently, and disappear without a trace.',
                'price' => '44.99',
                'discount_price' => '35.99',
                'discount_pct' => 20,
                'is_discounted' => true,
                'release_date' => '2025-04-05',
                'developer' => 'Black Ops Interactive',
                'publisher' => 'StealthWorks',
                'genre' => 'Action',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Shadow+Strike',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Shadow+Strike',
                'rating_avg' => 4.3,
                'rating_count' => 780,
                'coming_soon' => false,
            ],
            [
                'id' => 6,
                'title' => 'Mystic Woods',
                'slug' => 'mystic-woods',
                'description' => 'A magical forest holds secrets that could change the world forever.',
                'about' => 'Mystic Woods is a story-driven RPG set in an enchanted forest. Befriend mythical creatures, solve ancient riddles, and uncover the forest\'s heart.',
                'price' => '34.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-07-22',
                'developer' => 'Enchanted Byte',
                'publisher' => 'Fantasy World Entertainment',
                'genre' => 'RPG',
                'platforms' => ['windows', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Mystic+Woods',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Mystic+Woods',
                'rating_avg' => 4.6,
                'rating_count' => 1500,
                'coming_soon' => false,
            ],
            [
                'id' => 7,
                'title' => 'Racing Evolution',
                'slug' => 'racing-evolution',
                'description' => 'Feel the need for speed in the most realistic racing game ever made.',
                'about' => 'Racing Evolution features over 200 licensed cars, real-world tracks, and cutting-edge physics. Compete online or master the career mode.',
                'price' => '49.99',
                'discount_price' => '37.49',
                'discount_pct' => 25,
                'is_discounted' => true,
                'release_date' => '2024-09-15',
                'developer' => 'Turbocharge Games',
                'publisher' => 'Speedway Interactive',
                'genre' => 'Sports',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Racing+Evolution',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Racing+Evolution',
                'rating_avg' => 3.9,
                'rating_count' => 3400,
                'coming_soon' => false,
            ],
            [
                'id' => 8,
                'title' => 'Galactic War',
                'slug' => 'galactic-war',
                'description' => 'Command fleets and conquer galaxies in this grand strategy epic.',
                'about' => 'Galactic War is a 4X strategy game spanning the entire Milky Way. Research technologies, build armadas, and forge interstellar empires.',
                'price' => '19.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-05-10',
                'developer' => 'StarCraft Studios',
                'publisher' => 'Grand Strategy Inc',
                'genre' => 'Strategy',
                'platforms' => ['windows', 'mac', 'linux'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Galactic+War',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Galactic+War',
                'rating_avg' => 4.1,
                'rating_count' => 890,
                'coming_soon' => false,
            ],
            [
                'id' => 9,
                'title' => 'Haunted Asylum',
                'slug' => 'haunted-asylum',
                'description' => 'Survive the horrors that lurk within the abandoned wards.',
                'about' => 'Haunted Asylum is a first-person horror game set in a decaying psychiatric hospital. Explore, hide, and survive as unspeakable horrors hunt you.',
                'price' => '29.99',
                'discount_price' => '17.99',
                'discount_pct' => 40,
                'is_discounted' => true,
                'release_date' => '2024-10-31',
                'developer' => 'Dark Alley Games',
                'publisher' => 'Horror Interactive',
                'genre' => 'Horror',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Haunted+Asylum',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Haunted+Asylum',
                'rating_avg' => 4.4,
                'rating_count' => 1800,
                'coming_soon' => false,
            ],
            [
                'id' => 10,
                'title' => 'Pixel Quest',
                'slug' => 'pixel-quest',
                'description' => 'A nostalgic adventure through a beautifully crafted pixel world.',
                'about' => 'Pixel Quest is a love letter to classic adventure games. Journey through vibrant pixel art landscapes, solve puzzles, and rescue the kingdom.',
                'price' => '14.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-03-01',
                'developer' => 'RetroForge',
                'publisher' => 'Pixel Perfect Games',
                'genre' => 'Adventure',
                'platforms' => ['windows', 'mac', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Pixel+Quest',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Pixel+Quest',
                'rating_avg' => 4.7,
                'rating_count' => 2200,
                'coming_soon' => false,
            ],
            [
                'id' => 11,
                'title' => 'Kingdom Reborn',
                'slug' => 'kingdom-reborn',
                'description' => 'Lead your kingdom from ruin to glory in this medieval strategy game.',
                'about' => 'Kingdom Reborn combines city-building with real-time strategy. Build your castle, raise armies, and forge alliances in a dynamic medieval world.',
                'price' => '39.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2025-02-14',
                'developer' => 'Castleforge Interactive',
                'publisher' => 'Grand Strategy Inc',
                'genre' => 'Strategy',
                'platforms' => ['windows', 'mac'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Kingdom+Reborn',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Kingdom+Reborn',
                'rating_avg' => 4.3,
                'rating_count' => 720,
                'coming_soon' => false,
            ],
            [
                'id' => 12,
                'title' => 'Frozen Tundra',
                'slug' => 'frozen-tundra',
                'description' => 'Brave the arctic wasteland in this survival action game.',
                'about' => 'Frozen Tundra drops you into a brutal arctic wilderness. Hunt, build shelter, and fight off hostile wildlife to survive the eternal winter.',
                'price' => '44.99',
                'discount_price' => '38.24',
                'discount_pct' => 15,
                'is_discounted' => true,
                'release_date' => '2024-12-01',
                'developer' => 'North Pole Studios',
                'publisher' => 'SurvivalCraft',
                'genre' => 'Action',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Frozen+Tundra',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Frozen+Tundra',
                'rating_avg' => 4.0,
                'rating_count' => 430,
                'coming_soon' => false,
            ],
            [
                'id' => 13,
                'title' => 'Space Marines',
                'slug' => 'space-marines',
                'description' => 'Join the elite forces defending Earth from alien threats.',
                'about' => 'Space Marines is a fast-paced sci-fi shooter. Battle alien hordes, pilot mechs, and save humanity in this explosive action spectacle.',
                'price' => '59.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2025-05-20',
                'developer' => 'Orbital Games',
                'publisher' => 'Digital Dreams Publishing',
                'genre' => 'Sci-Fi',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Space+Marines',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Space+Marines',
                'rating_avg' => 3.8,
                'rating_count' => 560,
                'coming_soon' => false,
            ],
            [
                'id' => 14,
                'title' => 'The Lost City',
                'slug' => 'the-lost-city',
                'description' => 'Discover the secrets of an ancient civilization buried beneath the sand.',
                'about' => 'The Lost City is an archaeological adventure game. Excavate ruins, decipher hieroglyphs, and unravel the mystery of a forgotten civilization.',
                'price' => '24.99',
                'discount_price' => '17.49',
                'discount_pct' => 30,
                'is_discounted' => true,
                'release_date' => '2024-08-15',
                'developer' => 'Desert Fox Studios',
                'publisher' => 'Pixel Perfect Games',
                'genre' => 'Adventure',
                'platforms' => ['windows', 'mac', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=The+Lost+City',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=The+Lost+City',
                'rating_avg' => 4.5,
                'rating_count' => 1100,
                'coming_soon' => false,
            ],
            [
                'id' => 15,
                'title' => 'Farming Tycoon',
                'slug' => 'farming-tycoon',
                'description' => 'Build your agricultural empire from a single plot of land.',
                'about' => 'Farming Tycoon lets you experience the full cycle of modern farming. Plant crops, raise livestock, and expand your farm into a agribusiness empire.',
                'price' => '19.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-04-10',
                'developer' => 'Green Fields Interactive',
                'publisher' => 'Simulation Masters',
                'genre' => 'Simulation',
                'platforms' => ['windows', 'mac', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Farming+Tycoon',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Farming+Tycoon',
                'rating_avg' => 4.2,
                'rating_count' => 890,
                'coming_soon' => false,
            ],
            [
                'id' => 16,
                'title' => 'Night Stalkers',
                'slug' => 'night-stalkers',
                'description' => 'They only come out at night. And they are hungry.',
                'about' => 'Night Stalkers is a survival horror game where vampiric creatures hunt you through a dark city. Use light as your weapon and survive until dawn.',
                'price' => '34.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2025-07-20',
                'developer' => 'Dark Alley Games',
                'publisher' => 'Horror Interactive',
                'genre' => 'Horror',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Night+Stalkers',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Night+Stalkers',
                'rating_avg' => 4.1,
                'rating_count' => 340,
                'coming_soon' => false,
            ],
            [
                'id' => 17,
                'title' => 'Ultimate Fighter',
                'slug' => 'ultimate-fighter',
                'description' => 'Step into the ring and become the champion.',
                'about' => 'Ultimate Fighter is the most realistic MMA simulation ever. Create your fighter, train skills, and climb the rankings to become the undisputed champion.',
                'price' => '49.99',
                'discount_price' => '32.49',
                'discount_pct' => 35,
                'is_discounted' => true,
                'release_date' => '2024-06-30',
                'developer' => 'Knockout Games',
                'publisher' => 'Speedway Interactive',
                'genre' => 'Sports',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Ultimate+Fighter',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Ultimate+Fighter',
                'rating_avg' => 3.7,
                'rating_count' => 1200,
                'coming_soon' => false,
            ],
            [
                'id' => 18,
                'title' => 'Dungeon Crawlers',
                'slug' => 'dungeon-crawlers',
                'description' => 'Gather your party and venture into the depths of the underworld.',
                'about' => 'Dungeon Crawlers is a classic dungeon-crawling RPG. Build your party, explore procedurally generated dungeons, and defeat the lords of the deep.',
                'price' => '44.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-12-15',
                'developer' => 'Mythic Studios',
                'publisher' => 'Fantasy World Entertainment',
                'genre' => 'RPG',
                'platforms' => ['windows', 'mac', 'linux', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Dungeon+Crawlers',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Dungeon+Crawlers',
                'rating_avg' => 4.6,
                'rating_count' => 980,
                'coming_soon' => false,
            ],
            [
                'id' => 19,
                'title' => 'Ocean Explorer',
                'slug' => 'ocean-explorer',
                'description' => 'Dive into the depths of the ocean and discover its wonders.',
                'about' => 'Ocean Explorer is an underwater adventure game. Pilot your submarine through coral reefs, trenches, and encounter majestic sea creatures.',
                'price' => '29.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2025-08-01',
                'developer' => 'Deep Blue Interactive',
                'publisher' => 'Pixel Perfect Games',
                'genre' => 'Adventure',
                'platforms' => ['windows', 'playstation', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Ocean+Explorer',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Ocean+Explorer',
                'rating_avg' => 4.0,
                'rating_count' => 290,
                'coming_soon' => false,
            ],
            [
                'id' => 20,
                'title' => 'Tower Defense X',
                'slug' => 'tower-defense-x',
                'description' => 'Build, upgrade, and defend against endless waves of enemies.',
                'about' => 'Tower Defense X reinvents the genre with dynamic lanes, combo towers, and epic boss waves. Strategy is everything.',
                'price' => '9.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-02-14',
                'developer' => 'Strategy First',
                'publisher' => 'Grand Strategy Inc',
                'genre' => 'Strategy',
                'platforms' => ['windows', 'mac', 'linux', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Tower+Defense+X',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Tower+Defense+X',
                'rating_avg' => 4.4,
                'rating_count' => 1500,
                'coming_soon' => false,
            ],
            [
                'id' => 21,
                'title' => 'Neo Tokyo Drift',
                'slug' => 'neo-tokyo-drift',
                'description' => 'Street racing meets cyberpunk in the neon-lit streets of Neo Tokyo.',
                'about' => 'Neo Tokyo Drift combines high-speed street racing with a cyberpunk aesthetic. Customize your ride, compete in underground races, and build your reputation.',
                'price' => '39.99',
                'discount_price' => '21.99',
                'discount_pct' => 45,
                'is_discounted' => true,
                'release_date' => '2025-09-15',
                'developer' => 'Turbocharge Games',
                'publisher' => 'Speedway Interactive',
                'genre' => 'Action',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Neo+Tokyo+Drift',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Neo+Tokyo+Drift',
                'rating_avg' => 4.2,
                'rating_count' => 670,
                'coming_soon' => false,
            ],
            [
                'id' => 22,
                'title' => 'Fantasy Realm',
                'slug' => 'fantasy-realm',
                'description' => 'A sprawling open-world RPG where your choices shape the world.',
                'about' => 'Fantasy Realm offers an unprecedented level of freedom. Explore a vast open world, complete quests your way, and shape the fate of the realm.',
                'price' => '54.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-01-20',
                'developer' => 'Mythic Studios',
                'publisher' => 'Fantasy World Entertainment',
                'genre' => 'RPG',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Fantasy+Realm',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Fantasy+Realm',
                'rating_avg' => 4.8,
                'rating_count' => 3100,
                'coming_soon' => false,
            ],
            [
                'id' => 23,
                'title' => 'Zombie Outbreak',
                'slug' => 'zombie-outbreak',
                'description' => 'The apocalypse is here. How long can you survive?',
                'about' => 'Zombie Outbreak is a survival horror game set in a post-apocalyptic world overrun by the undead. Scavenge, craft, and fight to stay alive.',
                'price' => '24.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-10-05',
                'developer' => 'Undead Labs',
                'publisher' => 'Horror Interactive',
                'genre' => 'Horror',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Zombie+Outbreak',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Zombie+Outbreak',
                'rating_avg' => 3.9,
                'rating_count' => 2100,
                'coming_soon' => false,
            ],
            [
                'id' => 24,
                'title' => 'Construction Sim',
                'slug' => 'construction-sim',
                'description' => 'Build massive structures with realistic construction machinery.',
                'about' => 'Construction Sim puts you in the operator\'s seat of over 50 licensed vehicles. Build skyscrapers, bridges, and dams in career mode or free play.',
                'price' => '34.99',
                'discount_price' => '27.99',
                'discount_pct' => 20,
                'is_discounted' => true,
                'release_date' => '2024-03-15',
                'developer' => 'BuildMaster Games',
                'publisher' => 'Simulation Masters',
                'genre' => 'Simulation',
                'platforms' => ['windows', 'mac', 'playstation'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Construction+Sim',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Construction+Sim',
                'rating_avg' => 4.3,
                'rating_count' => 780,
                'coming_soon' => false,
            ],
            [
                'id' => 25,
                'title' => 'Astro Miner',
                'slug' => 'astro-miner',
                'description' => 'Mine asteroids, build your ship, explore the galaxy.',
                'about' => 'Astro Miner combines base building, exploration, and resource management in a vast procedurally generated asteroid belt.',
                'price' => '19.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2025-10-01',
                'developer' => 'Cosmic Forge',
                'publisher' => 'Stellar Interactive',
                'genre' => 'Sci-Fi',
                'platforms' => ['windows', 'mac', 'linux'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Astro+Miner',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Astro+Miner',
                'rating_avg' => 4.1,
                'rating_count' => 450,
                'coming_soon' => false,
            ],
            [
                'id' => 26,
                'title' => 'Legend of the Blade',
                'slug' => 'legend-of-the-blade',
                'description' => 'Master the blade and become the warrior of prophecy.',
                'about' => 'Legend of the Blade is a Japanese-inspired action game. Master various sword styles, learn devastating combos, and defeat demonic forces.',
                'price' => '49.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2025-11-15',
                'developer' => 'NeonPixel Games',
                'publisher' => 'Digital Dreams Publishing',
                'genre' => 'Action',
                'platforms' => ['windows', 'playstation', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Legend+of+the+Blade',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Legend+of+the+Blade',
                'rating_avg' => 4.7,
                'rating_count' => 890,
                'coming_soon' => false,
            ],
            [
                'id' => 27,
                'title' => "Pirate's Bounty",
                'slug' => 'pirates-bounty',
                'description' => 'Hoist the sails and seek treasure on the high seas!',
                'about' => 'Pirate\'s Bounty is a swashbuckling adventure game. Sail the Caribbean, engage in naval battles, dig for treasure, and become the most feared pirate.',
                'price' => '29.99',
                'discount_price' => '14.99',
                'discount_pct' => 50,
                'is_discounted' => true,
                'release_date' => '2024-09-19',
                'developer' => 'Sea Dog Studios',
                'publisher' => 'Pixel Perfect Games',
                'genre' => 'Adventure',
                'platforms' => ['windows', 'playstation', 'xbox', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Pirate%27s+Bounty',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Pirate%27s+Bounty',
                'rating_avg' => 4.4,
                'rating_count' => 1300,
                'coming_soon' => false,
            ],
            [
                'id' => 28,
                'title' => 'Grand Prix Manager',
                'slug' => 'grand-prix-manager',
                'description' => 'Manage your Formula One team to championship glory.',
                'about' => 'Grand Prix Manager puts you in charge of a racing team. Hire drivers, develop the car, manage finances, and compete for the world championship.',
                'price' => '39.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2025-04-20',
                'developer' => 'Pit Crew Interactive',
                'publisher' => 'Speedway Interactive',
                'genre' => 'Sports',
                'platforms' => ['windows', 'mac'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Grand+Prix+Manager',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Grand+Prix+Manager',
                'rating_avg' => 4.0,
                'rating_count' => 560,
                'coming_soon' => false,
            ],
            [
                'id' => 29,
                'title' => 'Dark Descent',
                'slug' => 'dark-descent',
                'description' => 'Descend into madness in this psychological horror experience.',
                'about' => 'Dark Descent is a psychological horror game that blurs the line between reality and nightmare. Your mind is your greatest enemy.',
                'price' => '44.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-10-31',
                'developer' => 'Dark Alley Games',
                'publisher' => 'Horror Interactive',
                'genre' => 'Horror',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Dark+Descent',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Dark+Descent',
                'rating_avg' => 4.5,
                'rating_count' => 1600,
                'coming_soon' => false,
            ],
            [
                'id' => 30,
                'title' => 'Chess Master Elite',
                'slug' => 'chess-master-elite',
                'description' => 'The ultimate chess experience with AI-powered opponents.',
                'about' => 'Chess Master Elite features the most advanced chess AI ever created. Learn from grandmaster-level analysis, play online, and improve your game.',
                'price' => '9.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2024-01-05',
                'developer' => 'Strategy First',
                'publisher' => 'Grand Strategy Inc',
                'genre' => 'Strategy',
                'platforms' => ['windows', 'mac', 'linux', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Chess+Master+Elite',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Chess+Master+Elite',
                'rating_avg' => 4.9,
                'rating_count' => 2800,
                'coming_soon' => false,
            ],
            [
                'id' => 31,
                'title' => 'Terraforming Mars',
                'slug' => 'terraforming-mars',
                'description' => 'Transform the Red Planet into a new home for humanity.',
                'about' => 'Terraforming Mars is a deep simulation game where you manage resources, develop technology, and gradually make Mars habitable for human colonization.',
                'price' => '49.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2026-08-01',
                'developer' => 'Cosmic Forge',
                'publisher' => 'Stellar Interactive',
                'genre' => 'Simulation',
                'platforms' => ['windows', 'mac'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Terraforming+Mars',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Terraforming+Mars',
                'rating_avg' => 4.6,
                'rating_count' => 0,
                'coming_soon' => true,
            ],
            [
                'id' => 32,
                'title' => 'Cyberpunk 2078',
                'slug' => 'cyberpunk-2078',
                'description' => 'The future is brutal. Forge your legend in the dark metropolis.',
                'about' => 'Cyberpunk 2078 is the next generation of open-world RPGs. Set in a massive dystopian city, every choice shapes your story and the world around you.',
                'price' => '69.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2026-12-15',
                'developer' => 'NeonPixel Games',
                'publisher' => 'Digital Dreams Publishing',
                'genre' => 'RPG',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Cyberpunk+2078',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Cyberpunk+2078',
                'rating_avg' => 4.9,
                'rating_count' => 0,
                'coming_soon' => true,
            ],
            [
                'id' => 33,
                'title' => 'Battle Royale X',
                'slug' => 'battle-royale-x',
                'description' => '100 players. One winner. Drop in and fight.',
                'about' => 'Battle Royale X is the ultimate free-to-play battle royale experience. Drop onto a massive island, loot weapons, and be the last one standing.',
                'price' => '0',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2026-07-01',
                'developer' => 'Orbital Games',
                'publisher' => 'Digital Dreams Publishing',
                'genre' => 'Action',
                'platforms' => ['windows', 'playstation', 'xbox', 'nintendo'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Battle+Royale+X',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Battle+Royale+X',
                'rating_avg' => 4.0,
                'rating_count' => 0,
                'coming_soon' => true,
            ],
            [
                'id' => 34,
                'title' => 'Ninja Gaiden Reborn',
                'slug' => 'ninja-gaiden-reborn',
                'description' => 'The legendary ninja returns in an all-new adventure.',
                'about' => 'Ninja Gaiden Reborn revitalizes the classic franchise with modern graphics, refined combat mechanics, and an expansive new storyline.',
                'price' => '59.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2026-09-01',
                'developer' => 'NeonPixel Games',
                'publisher' => 'Digital Dreams Publishing',
                'genre' => 'Action',
                'platforms' => ['windows', 'playstation', 'xbox'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Ninja+Gaiden+Reborn',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Ninja+Gaiden+Reborn',
                'rating_avg' => 4.7,
                'rating_count' => 0,
                'coming_soon' => true,
            ],
            [
                'id' => 35,
                'title' => 'Star Citizen New',
                'slug' => 'star-citizen-new',
                'description' => 'The ultimate space simulation experience arrives.',
                'about' => 'Star Citizen New is the most ambitious space sim ever created. Explore a 1:1 scale galaxy, engage in ship-to-ship combat, and build your legacy among the stars.',
                'price' => '44.99',
                'discount_price' => null,
                'discount_pct' => null,
                'is_discounted' => false,
                'release_date' => '2026-11-01',
                'developer' => 'Cosmic Forge',
                'publisher' => 'Stellar Interactive',
                'genre' => 'Sci-Fi',
                'platforms' => ['windows'],
                'cover' => 'https://placehold.co/300x400/2a475e/1a9fff?text=Star+Citizen+New',
                'header' => 'https://placehold.co/1200x400/171a21/1a9fff?text=Star+Citizen+New',
                'rating_avg' => 3.5,
                'rating_count' => 0,
                'coming_soon' => true,
            ],
        ];
    }
}
